/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 door_model.glb 
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useHelper } from '@react-three/drei';
import { useDoorStore } from '@/store/door_store';
import DOOR_VALUES from '@/utils/door_config';
import { useGlassMaterial, useMaterial } from './AllMaterials';
import { getHardwareColour } from '@/utils/3d_utils/3d_utils';

import { getMetrics } from '@/utils/3d_utils/3d_utils';
import * as THREE from 'three';

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/door_model.glb');
  const [BASE_BAND_WORLD_X_POS, set_BASE_BAND_WORLD_X] = useState();

  /* ===============================
     GLOBAL STORE VALUES
  =============================== */
  const verglasung = useDoorStore((s) => s.door.verglasung);
  const doorWidth = useDoorStore((s) => s.door.width);
  const doorHeight = useDoorStore((s) => s.door.height);
  const schloss = useDoorStore((s) => s.door.schloss);
  const doorType = useDoorStore((s) => s.door.doorType);
  const anschlag = useDoorStore((s) => s.door.anschlag);
  const zargen = useDoorStore((s) => s.door.zarge);
  const band = useDoorStore((s) => s.door.band);
  const boden = useDoorStore((s) => s.door.boden);

  const door_collection_ref = useRef();
  const frame_collection_ref = useRef();
  const lock_collection_front_ref = useRef();
  const lock_collection_back_ref = useRef();
  const bander_collection_ref = useRef();
  const rebate_edge_ref = useRef();
  const bboxHelperRef = useRef();

  /* ===============================
     BASE MODEL DIMENSIONS (GLB SIZE)
  =============================== */
  const BASE_WIDTH = 900;
  const BASE_HEIGHT = 2100;

  /* ===============================
     SCALE CALCULATION
  =============================== */
  const doorScaleX = doorWidth / BASE_WIDTH;
  const doorScaleY = doorHeight / BASE_HEIGHT;

  /* ===============================
     MATERIALS
  =============================== */
  const glassMat = useGlassMaterial(verglasung);
  const hardwareMat = useMaterial(getHardwareColour(schloss));
  const BandMat = useMaterial(getHardwareColour(band));

  const mat = {
    door: materials.Material,
    glass: glassMat ?? nodes.dc_glass.material,
    handle: hardwareMat ?? nodes.lcf_front_handle.material,
    rebateEdge: nodes.dc_rebate_edge.material,
    bodendichtungFill: nodes.dc_bodendictung_fill.material,
    bodendichtungConstruct1: nodes.dc_bodendictung_construct_1.material,
    bodendichtungConstruct2: nodes.dc_bodendictung_construct_2.material,
    bodendichtungConstruct3: nodes.dc_bodendictung_construct_3.material,
    zargen: nodes.fc_zargen.material,
    banderTop: BandMat ?? nodes.bc_2_tlg_bander_top.material,
    banderBottom: BandMat ?? nodes.bc_2_tlg_bander_bottom.material,
    frontFullLockFrame: hardwareMat ?? nodes.lcf_front_full_lock_frame.material,
    frontPzwLock: hardwareMat ?? nodes.lcf_front_pzw_lock.material,
    frontWcLock: hardwareMat ?? nodes.lcf_front_wc_lock.material,
    frontBbLock: hardwareMat ?? nodes.lcf_front_bb_lock.material,
    frontHalfLockFrameTop: hardwareMat ?? nodes.lcf_front_half_lock_frame_top.material,
    frontHalfLockFrameBottom: hardwareMat ?? nodes.lcf_front_half_lock_frame_bottom.material,
    backFullLockFrame: hardwareMat ?? nodes.lcb_back_lcb_full_lock_frame_back.material,
    backPzwLock: hardwareMat ?? nodes.lcb_back_pzw_lock_back.material,
    backWcLock: hardwareMat ?? nodes.lcb_back_wc_lock_back.material,
    backBbLock: hardwareMat ?? nodes.lcb_back_bb_lock_back.material,
    backHalfLockFrameTop: hardwareMat ?? nodes.lcb_back_half_lock_frame_top.material,
    backHalfLockFrameBottom: hardwareMat ?? nodes.lcb_back_half_lock_frame_bottom.material,
  };

  /* ===============================
     ELEMENT VISIBILITY
  =============================== */
  const visibility = {
    zargen: zargen !== DOOR_VALUES.ZARGEN_OPTIONS.OHNE_ZARGEN,
    schloss: schloss !== DOOR_VALUES.LOCK_OPTIONS.OHNE,
    boden: boden !== DOOR_VALUES.BODENDICHTUNG.OHNE_BODENDICHTUNG,

    isBB: schloss.includes('BB'),
    isWC: schloss.includes('WC'),
    isPZ: schloss.includes('PZ'),
    isOhne: schloss === DOOR_VALUES.LOCK_OPTIONS.OHNE,
  };

  /* ===============================
     ANSCHLAG (MIRRORING)
  =============================== */
  const mirrorX = anschlag === DOOR_VALUES.ANSCHLAG_TYPES.DIN_RIGHT ? -1 : 1;

  /* ===============================
     BANDER METRICS — recalculate every 3 seconds
  =============================== */

  useEffect(() => {
    const door_metrics = getMetrics(door_collection_ref, {
      addBoundingBox: true,
      color: 0xff0000,
    });

    console.log('Door metrics: ', door_metrics);

    let band_pos_x = 0;

    if (mirrorX == 1) {
      band_pos_x = door_metrics.maxX - door_metrics.maxX / doorScaleX;
    } else {
      // band_pos_x = door_metrics.minX - Math.abs(door_metrics.minX / doorScaleX);
      band_pos_x = door_metrics.maxX - door_metrics.maxX / doorScaleX;
      band_pos_x -= door_metrics.centerX;
    }
    bander_collection_ref.current.position.x = band_pos_x;
  }, [doorWidth, doorHeight, anschlag]); // ✅ re-runs when anschlag changes

  useHelper(bander_collection_ref, THREE.BoxHelper, 'green');

  return (
    <group {...props} scale={[mirrorX, 1, 1]} dispose={null}>
      {/* ── Door leaf ── */}
      <group ref={door_collection_ref} scale={[doorScaleX, doorScaleY, 1]} dispose={null}>
        <mesh geometry={nodes.dc_door.geometry} material={mat.door} />
        <mesh geometry={nodes.dc_glass.geometry} material={mat.glass} />
        <mesh ref={rebate_edge_ref} geometry={nodes.dc_rebate_edge.geometry} material={mat.rebateEdge} />
        <mesh geometry={nodes.dc_bodendictung_fill.geometry} visible={visibility.boden == false} material={mat.bodendichtungFill} />
        <mesh geometry={nodes.dc_bodendictung_construct_1.geometry} visible={visibility.boden} material={mat.bodendichtungConstruct1} />
        <mesh geometry={nodes.dc_bodendictung_construct_2.geometry} visible={visibility.boden} material={mat.bodendichtungConstruct2} />
        <mesh geometry={nodes.dc_bodendictung_construct_3.geometry} visible={visibility.boden} material={mat.bodendichtungConstruct3} />
      </group>

      {/* ── Frame / Zarge ── */}
      <group ref={frame_collection_ref} visible={visibility.zargen} scale={[doorScaleX, doorScaleY, 1]} dispose={null}>
        <mesh geometry={nodes.fc_zargen.geometry} material={mat.zargen} />
      </group>

      {/* ── Hinges / Bänder ── */}
      <group ref={bander_collection_ref} dispose={null}>
        <mesh geometry={nodes.bc_2_tlg_bander_top.geometry} material={mat.banderTop} />
        <mesh geometry={nodes.bc_2_tlg_bander_bottom.geometry} material={mat.banderBottom} />
      </group>

      {/* ── Lock — front face ── */}
      <group ref={lock_collection_front_ref} dispose={null}>
        <mesh geometry={nodes.lcf_front_full_lock_frame.geometry} visible={false} material={mat.frontFullLockFrame} />
        <mesh geometry={nodes.lcf_front_pzw_lock.geometry} visible={visibility.isPZ} material={mat.frontPzwLock} />
        <mesh geometry={nodes.lcf_front_handle.geometry} material={mat.handle} />
        <mesh geometry={nodes.lcf_front_wc_lock.geometry} visible={visibility.isWC} material={mat.frontWcLock} />
        <mesh geometry={nodes.lcf_front_bb_lock.geometry} visible={visibility.isBB} material={mat.frontBbLock} />
        <mesh geometry={nodes.lcf_front_half_lock_frame_top.geometry} material={mat.frontHalfLockFrameTop} />
        <mesh geometry={nodes.lcf_front_half_lock_frame_bottom.geometry} material={mat.frontHalfLockFrameBottom} />
      </group>

      {/* ── Lock — back face ── */}
      <group ref={lock_collection_back_ref} dispose={null}>
        <mesh geometry={nodes.lcb_back_lcb_full_lock_frame_back.geometry} visible={false} material={mat.backFullLockFrame} />
        <mesh geometry={nodes.lcb_back_pzw_lock_back.geometry} visible={visibility.isPZ} material={mat.backPzwLock} />
        <mesh geometry={nodes.lcb_back_handle_back.geometry} material={mat.handle} />
        <mesh geometry={nodes.lcb_back_wc_lock_back.geometry} visible={visibility.isWC} material={mat.backWcLock} />
        <mesh geometry={nodes.lcb_back_bb_lock_back.geometry} visible={visibility.isBB} material={mat.backBbLock} />
        <mesh geometry={nodes.lcb_back_half_lock_frame_top.geometry} material={mat.backHalfLockFrameTop} />
        <mesh geometry={nodes.lcb_back_half_lock_frame_bottom.geometry} material={mat.backHalfLockFrameBottom} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/door_model.glb');
