/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/door_model.glb --output Door_model_new.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/door_model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.037, 2.146, 0.062]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0.289, 2.018, 0.112]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0.289, 2.018, 0.112]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.dc_door.geometry} material={materials.Material} />
      <mesh geometry={nodes.dc_glass.geometry} material={nodes.dc_glass.material} scale={[1.011, 1, 1]} />
      <mesh geometry={nodes.dc_rebate_edge.geometry} material={nodes.dc_rebate_edge.material} />
      <mesh geometry={nodes.dc_vent_top.geometry} material={nodes.dc_vent_top.material} />
      <mesh geometry={nodes.dc_vent_bottom.geometry} material={nodes.dc_vent_bottom.material} />
      <mesh geometry={nodes.dc_bodendictung_fill.geometry} material={nodes.dc_bodendictung_fill.material} />
      <mesh geometry={nodes.dc_bodendictung_construct_1.geometry} material={nodes.dc_bodendictung_construct_1.material} />
      <mesh geometry={nodes.dc_bodendictung_construct_2.geometry} material={nodes.dc_bodendictung_construct_2.material} />
      <mesh geometry={nodes.dc_bodendictung_construct_3.geometry} material={nodes.dc_bodendictung_construct_3.material} />
      <mesh geometry={nodes.fc_zargen.geometry} material={nodes.fc_zargen.material} />
      <mesh geometry={nodes.fc_zargen_cut.geometry} material={nodes.fc_zargen_cut.material} />
      <mesh geometry={nodes.bc_2_tlg_bander_top.geometry} material={nodes.bc_2_tlg_bander_top.material} />
      <mesh geometry={nodes.bc_2_tlg_bander_bottom.geometry} material={nodes.bc_2_tlg_bander_bottom.material} />
      <mesh geometry={nodes.bc_pivot_bander_top_top_2nd_half.geometry} material={nodes.bc_pivot_bander_top_top_2nd_half.material} />
      <mesh geometry={nodes.bc_pivot_bander_top_top_1st_half.geometry} material={nodes.bc_pivot_bander_top_top_1st_half.material} />
      <mesh geometry={nodes.bc_pivot_bander_bottom_top_2nd_half.geometry} material={nodes.bc_pivot_bander_bottom_top_2nd_half.material} />
      <mesh geometry={nodes.bc_pivot_bander_bottom_1st_half.geometry} material={nodes.bc_pivot_bander_bottom_1st_half.material} />
      <mesh geometry={nodes.lcf_front_full_lock_frame.geometry} material={nodes.lcf_front_full_lock_frame.material} />
      <mesh geometry={nodes.lcf_front_pzw_lock.geometry} material={nodes.lcf_front_pzw_lock.material} />
      <mesh geometry={nodes.lcf_front_handle.geometry} material={nodes.lcf_front_handle.material} />
      <mesh geometry={nodes.lcf_front_wc_lock.geometry} material={nodes.lcf_front_wc_lock.material} />
      <mesh geometry={nodes.lcf_front_bb_lock.geometry} material={nodes.lcf_front_bb_lock.material} />
      <mesh geometry={nodes.lcf_front_half_lock_frame_top.geometry} material={nodes.lcf_front_half_lock_frame_top.material} />
      <mesh geometry={nodes.lcf_front_half_lock_frame_bottom.geometry} material={nodes.lcf_front_half_lock_frame_bottom.material} />
      <mesh geometry={nodes.lcb_back_lcb_full_lock_frame_back.geometry} material={nodes.lcb_back_lcb_full_lock_frame_back.material} />
      <mesh geometry={nodes.lcb_back_pzw_lock_back.geometry} material={nodes.lcb_back_pzw_lock_back.material} />
      <mesh geometry={nodes.lcb_back_handle_back.geometry} material={nodes.lcb_back_handle_back.material} />
      <mesh geometry={nodes.lcb_back_wc_lock_back.geometry} material={nodes.lcb_back_wc_lock_back.material} />
      <mesh geometry={nodes.lcb_back_bb_lock_back.geometry} material={nodes.lcb_back_bb_lock_back.material} />
      <mesh geometry={nodes.lcb_back_half_lock_frame_top.geometry} material={nodes.lcb_back_half_lock_frame_top.material} />
      <mesh geometry={nodes.lcb_back_half_lock_frame_bottom.geometry} material={nodes.lcb_back_half_lock_frame_bottom.material} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0.328, 2.146, -0.755]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0.328, 2.146, -0.664]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={-1} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-0.393, 2.146, -0.755]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-0.393, 2.146, -0.664]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={-1} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.305, 2.184, -0.711]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.869, 1]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[0.306, 2.096, -0.732]} rotation={[-Math.PI / 2, 1.257, 0]} scale={-0.567} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-0.415, 2.184, -0.711]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 0.869, 1]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-0.414, 2.096, -0.687]} rotation={[Math.PI / 2, -1.257, -Math.PI]} scale={0.567} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[0.306, 2.096, -0.687]} rotation={[Math.PI / 2, -1.257, -Math.PI]} scale={0.567} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-0.414, 2.096, -0.732]} rotation={[-Math.PI / 2, 1.257, 0]} scale={-0.567} />
      <mesh geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[0.346, 2.137, 0.089]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[-1.44, 2.137, 0.089]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={-1} />
      <mesh geometry={nodes.wc_wall.geometry} material={nodes.wc_wall.material} />
    </group>
  )
}

useGLTF.preload('/door_model.glb')
