/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/door_model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/door_model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dc_door.geometry} material={materials.Material} />
      <mesh geometry={nodes.dc_glass.geometry} material={nodes.dc_glass.material} />
      <mesh geometry={nodes.dc_rebate_edge.geometry} material={nodes.dc_rebate_edge.material} />
      <mesh geometry={nodes.dc_vent_top.geometry} material={nodes.dc_vent_top.material} />
      <mesh geometry={nodes.dc_vent_bottom.geometry} material={nodes.dc_vent_bottom.material} />
      <mesh geometry={nodes.dc_bodendictung_fill.geometry} material={nodes.dc_bodendictung_fill.material} />
      <mesh geometry={nodes.dc_bodendictung_construct_1.geometry} material={nodes.dc_bodendictung_construct_1.material} />
      <mesh geometry={nodes.dc_bodendictung_construct_2.geometry} material={nodes.dc_bodendictung_construct_2.material} />
      <mesh geometry={nodes.dc_bodendictung_construct_3.geometry} material={nodes.dc_bodendictung_construct_3.material} />
      <mesh geometry={nodes.fc_zargen.geometry} material={nodes.fc_zargen.material} />
      <mesh geometry={nodes.bc_2_tlg_bander_top.geometry} material={nodes.bc_2_tlg_bander_top.material} />
      <mesh geometry={nodes.bc_2_tlg_bander_bottom.geometry} material={nodes.bc_2_tlg_bander_bottom.material} />
      <mesh geometry={nodes.bc_pivot_bander_top_top_2nd_half.geometry} material={nodes.bc_pivot_bander_top_top_2nd_half.material} />
      <mesh geometry={nodes.bc_pivot_bander_top_top_1st_half.geometry} material={nodes.bc_pivot_bander_top_top_1st_half.material} />
      <mesh geometry={nodes.bc_pivot_bander_bottom_top_2nd_half.geometry} material={nodes.bc_pivot_bander_bottom_top_2nd_half.material} />
      <mesh geometry={nodes.bc_pivot_bander_bottom_1st_half.geometry} material={nodes.bc_pivot_bander_bottom_1st_half.material} />
      <mesh geometry={nodes.lcf_front_full_lock_frame.geometry} material={nodes.lcf_front_full_lock_frame.material} />
      <mesh geometry={nodes.lcf_front_pzw_lock.geometry} material={nodes.lcf_front_pzw_lock.material} />
      <mesh geometry={nodes.lcf_front_handle.geometry} material={nodes.lcf_front_handle.material} />
      <mesh geometry={nodes.lcf_front_wc_lock.geometry} material={nodes.lcf_front_wc_lock.material} />
      <mesh geometry={nodes.lcf_front_bb_lock.geometry} material={nodes.lcf_front_bb_lock.material} />
      <mesh geometry={nodes.lcf_front_half_lock_frame_top.geometry} material={nodes.lcf_front_half_lock_frame_top.material} />
      <mesh geometry={nodes.lcf_front_half_lock_frame_bottom.geometry} material={nodes.lcf_front_half_lock_frame_bottom.material} />
      <mesh geometry={nodes.lcb_back_lcb_full_lock_frame_back.geometry} material={nodes.lcb_back_lcb_full_lock_frame_back.material} />
      <mesh geometry={nodes.lcb_back_pzw_lock_back.geometry} material={nodes.lcb_back_pzw_lock_back.material} />
      <mesh geometry={nodes.lcb_back_handle_back.geometry} material={nodes.lcb_back_handle_back.material} />
      <mesh geometry={nodes.lcb_back_wc_lock_back.geometry} material={nodes.lcb_back_wc_lock_back.material} />
      <mesh geometry={nodes.lcb_back_bb_lock_back.geometry} material={nodes.lcb_back_bb_lock_back.material} />
      <mesh geometry={nodes.lcb_back_half_lock_frame_top.geometry} material={nodes.lcb_back_half_lock_frame_top.material} />
      <mesh geometry={nodes.lcb_back_half_lock_frame_bottom.geometry} material={nodes.lcb_back_half_lock_frame_bottom.material} />
    </group>
  )
}

useGLTF.preload('/door_model.glb')
