/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 door_model.glb 
*/

import React, { useEffect, useRef, useState, useMemo } from "react";
import { useGLTF, useHelper, useTexture } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { Geometry, Base, Subtraction } from "@react-three/csg";
import * as THREE from "three";
import { EXRLoader } from "three/addons/loaders/EXRLoader.js";
import { useDoorStore } from "@/store/door_store";
import { DOOR_VALUES } from "@/utils/door_config";
import {
  getHardwareColour,
  getMetrics,
  useGlassMaterial,
  useMaterial,
} from "@/utils/3d_utils/3d_utils";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/door_model.glb");

  /* ===============================
     GLOBAL STORE VALUES
  =============================== */
  const verglasung = useDoorStore((s) => s.door.verglasung_store);
  const doorWidth = useDoorStore((s) => s.door.width_store);
  const doorHeight = useDoorStore((s) => s.door.height_store);
  const schloss = useDoorStore((s) => s.door.schloss_store);
  const doorType = useDoorStore((s) => s.door.doorType_store);
  const anschlag = useDoorStore((s) => s.door.anschlag_store);
  const zargen = useDoorStore((s) => s.door.zarge_store);
  const band = useDoorStore((s) => s.door.band_store);
  const boden = useDoorStore((s) => s.door.boden_store);
  const vent = useDoorStore((s) => s.door.lueftung_store);

  const door_collection_ref = useRef();
  const sc_schiebe_collection_ref = useRef();
  const frame_collection_ref = useRef();
  const wall_collection_ref = useRef();
  const lock_collection_front_ref = useRef();
  const lock_collection_back_ref = useRef();
  const bander_collection_ref = useRef();
  const rebate_edge_ref = useRef();
  const bboxHelperRef = useRef();

  /* ===============================
     BASE MODEL DIMENSIONS (GLB SIZE)
  =============================== */
  const BASE_WIDTH = 900;
  const BASE_HEIGHT = 2100;

  /* ===============================
     SCALE CALCULATION
  =============================== */
  const doorScaleX = doorWidth / BASE_WIDTH;
  const doorScaleY = doorHeight / BASE_HEIGHT;

  /* ===============================
     MATERIALS
  =============================== */
  const glassMat = useGlassMaterial(verglasung);
  const hardwareMat = useMaterial(getHardwareColour(schloss));
  const BandMat = useMaterial(getHardwareColour(band));

  const wallTextures = useTexture(
    {
      map: "/textures/round-pattern-wall_texture/round-pattern-wallpaper1_albedo.png",
      aoMap:
        "/textures/round-pattern-wall_texture/round-pattern-wallpaper1_ao.png",
      metalnessMap:
        "/textures/round-pattern-wall_texture/round-pattern-wallpaper1_metallic.png",
      normalMap:
        "/textures/round-pattern-wall_texture/round-pattern-wallpaper1_normal-ogl.png",
      roughnessMap:
        "/textures/round-pattern-wall_texture/round-pattern-wallpaper1_roughness.png",
    },
    (textures) => {
      Object.values(textures).forEach((t) => {
        t.wrapS = t.wrapT = THREE.RepeatWrapping;
        t.needsUpdate = true;
      });
    },
  );

  const [floorDiff, floorDisp] = useTexture([
    "/textures/plank_flooring_textures/plank_flooring_04_diff_4k.jpg",
    "/textures/plank_flooring_textures/plank_flooring_04_disp_4k.jpg",
  ]);
  const floorNor = useLoader(
    EXRLoader,
    "/textures/plank_flooring_textures/plank_flooring_04_nor_gl_4k.exr",
  );
  const floorRough = useLoader(
    EXRLoader,
    "/textures/plank_flooring_textures/plank_flooring_04_rough_4k.exr",
  );
  useMemo(() => {
    [floorDiff, floorDisp, floorNor, floorRough].forEach((t) => {
      t.wrapS = t.wrapT = THREE.RepeatWrapping;
      t.repeat.set(200, 200);
      t.needsUpdate = true;
    });
  }, [floorDiff, floorDisp, floorNor, floorRough]);

  // Rebuild wall UVs from local XY positions — bypasses the mesh's UV map
  // so the texture tiles uniformly. Increase WALL_TILE_SCALE for bigger tiles,
  // decrease for smaller/more tiles.
  const WALL_TILE_SCALE = 2;
  const wallGeom = useMemo(() => {
    const geom = nodes.wc_wall.geometry.clone();
    const pos = geom.attributes.position;
    const uvs = new Float32Array(pos.count * 2);
    for (let i = 0; i < pos.count; i++) {
      uvs[i * 2] = pos.getX(i) / WALL_TILE_SCALE;
      uvs[i * 2 + 1] = pos.getY(i) / WALL_TILE_SCALE;
    }
    geom.setAttribute("uv", new THREE.BufferAttribute(uvs, 2));
    return geom;
  }, [nodes.wc_wall.geometry]);

  const mat = {
    door: materials.Material,
    glass: glassMat ?? nodes.dc_glass.material,
    handle: hardwareMat ?? nodes.lcf_front_handle.material,
    rebateEdge: nodes.dc_rebate_edge.material,
    bodendichtungFill: nodes.dc_bodendictung_fill.material,
    bodendichtungConstruct1: nodes.dc_bodendictung_construct_1.material,
    bodendichtungConstruct2: nodes.dc_bodendictung_construct_2.material,
    bodendichtungConstruct3: nodes.dc_bodendictung_construct_3.material,
    zargen: nodes.fc_zargen.material,
    banderTop: BandMat ?? nodes.bc_2_tlg_bander_top.material,
    banderBottom: BandMat ?? nodes.bc_2_tlg_bander_bottom.material,
    banderPivotTop: BandMat ?? nodes.bc_pivot_bander_top_top_1st_half.material,
    banderPivotBottom:
      BandMat ?? nodes.bc_pivot_bander_top_top_1st_half.material,
    frontFullLockFrame: hardwareMat ?? nodes.lcf_front_full_lock_frame.material,
    frontPzwLock: hardwareMat ?? nodes.lcf_front_pzw_lock.material,
    frontWcLock: hardwareMat ?? nodes.lcf_front_wc_lock.material,
    frontBbLock: hardwareMat ?? nodes.lcf_front_bb_lock.material,
    frontHalfLockFrameTop:
      hardwareMat ?? nodes.lcf_front_half_lock_frame_top.material,
    frontHalfLockFrameBottom:
      hardwareMat ?? nodes.lcf_front_half_lock_frame_bottom.material,
    backFullLockFrame:
      hardwareMat ?? nodes.lcb_back_lcb_full_lock_frame_back.material,
    backPzwLock: hardwareMat ?? nodes.lcb_back_pzw_lock_back.material,
    backWcLock: hardwareMat ?? nodes.lcb_back_wc_lock_back.material,
    backBbLock: hardwareMat ?? nodes.lcb_back_bb_lock_back.material,
    backHalfLockFrameTop:
      hardwareMat ?? nodes.lcb_back_half_lock_frame_top.material,
    backHalfLockFrameBottom:
      hardwareMat ?? nodes.lcb_back_half_lock_frame_bottom.material,
  };

  /* ===============================
     ELEMENT VISIBILITY
  =============================== */
  const visibility = {
    zargen: zargen !== DOOR_VALUES.ZARGEN_OPTIONS.OHNE_ZARGEN,
    schloss: schloss !== DOOR_VALUES.LOCK_OPTIONS.OHNE,
    boden: boden !== DOOR_VALUES.BODENDICHTUNG.OHNE_BODENDICHTUNG,
    rebateEdge: doorType === DOOR_VALUES.TURTYP_OPTION.Gefalzt,
    glass: verglasung !== DOOR_VALUES.VERGLASUNG_OPTIONS.OHNE_VERGLASUNG,
    wall: doorType === DOOR_VALUES.TURTYP_OPTION.Schiebetur,

    topVent:
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.UNTEN ||
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.UNTEN_UND_OBEN,
    bottomVent:
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.OBEN ||
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.UNTEN_UND_OBEN,

    isbander2tlg:
      doorType === DOOR_VALUES.TURTYP_OPTION.Gefalzt &&
      doorType !== DOOR_VALUES.TURTYP_OPTION.Schiebetur,
    isbanderPivot:
      doorType === DOOR_VALUES.TURTYP_OPTION.Stumpf &&
      doorType !== DOOR_VALUES.TURTYP_OPTION.Schiebetur,

    isBB: schloss.includes("BB"),
    isWC: schloss.includes("WC"),
    isPZ: schloss.includes("PZ"),
    isOhne: schloss === DOOR_VALUES.LOCK_OPTIONS.OHNE,
  };

  /* ===============================
     ANSCHLAG (MIRRORING)
  =============================== */
  const mirrorX = anschlag === DOOR_VALUES.ANSCHLAG_TYPES.DIN_RIGHT ? -1 : 1;

  /* ===============================
     BANDER METRICS — recalculate every 3 seconds
  =============================== */

  useEffect(() => {
    const door_metrics = getMetrics(door_collection_ref, {
      addBoundingBox: false,
      color: 0xff0000,
    });

    console.log("Door metrics: ", door_metrics);

    let band_pos_x = 0;
    let lock_collection_pos_x = 0;
    let sc_schiebe_collection_pos_y = 0;

    if (mirrorX == 1) {
      band_pos_x = door_metrics.maxX - door_metrics.maxX / doorScaleX;
      lock_collection_pos_x =
        door_metrics.minX - door_metrics.minX / doorScaleX;
    } else if (mirrorX == -1) {
      band_pos_x = door_metrics.minX / doorScaleX - door_metrics.minX;
      lock_collection_pos_x =
        door_metrics.maxX / doorScaleX - door_metrics.maxX;
    } 
     if (doorType === DOOR_VALUES.TURTYP_OPTION.Schiebetur) {
      sc_schiebe_collection_pos_y =
        door_metrics.maxY - door_metrics.maxY / doorScaleY;
        console.log("Schiebe door - sc_schiebe_collection_pos_y: ", sc_schiebe_collection_pos_y);
    }
    bander_collection_ref.current.position.x = band_pos_x;
    lock_collection_front_ref.current.position.x = lock_collection_pos_x;
    lock_collection_back_ref.current.position.x = lock_collection_pos_x;
    sc_schiebe_collection_ref.current.position.y = sc_schiebe_collection_pos_y;


  }, [doorWidth, doorHeight, anschlag, doorType]); // ✅ re-runs when anschlag changes

  /* ===============================
     FRAME/WALL POSITION — recalculate 
  =============================== */
  useEffect(() => {
    if (!frame_collection_ref.current) return;

    const isSchiebe = doorType === DOOR_VALUES.TURTYP_OPTION.Schiebetur;
    const zOffset = isSchiebe
      ? -0.015
      : doorType === DOOR_VALUES.TURTYP_OPTION.Gefalzt
        ? 0
        : 0.01;
    frame_collection_ref.current.position.z = zOffset;
wall_collection_ref.current.position.z = isSchiebe ? -0.015 : 0;
      
  }, [doorType]);

  return (
    <group {...props} scale={[mirrorX, 1, 1]} dispose={null}>
      {/* ── Door leaf ── */}
      <group
        ref={door_collection_ref}
        scale={[doorScaleX, doorScaleY, 1]}
        dispose={null}
      >
        <mesh geometry={nodes.dc_door.geometry} material={mat.door} />

        <mesh
          geometry={nodes.dc_glass.geometry}
          visible={visibility.glass}
          material={mat.glass}
        />
        <mesh
          ref={rebate_edge_ref}
          geometry={nodes.dc_rebate_edge.geometry}
          visible={visibility.rebateEdge}
          material={mat.rebateEdge}
        />
        <mesh
          geometry={nodes.dc_bodendictung_fill.geometry}
          visible={visibility.boden == false}
          material={mat.bodendichtungFill}
        />
        <mesh
          geometry={nodes.dc_bodendictung_construct_1.geometry}
          visible={visibility.boden}
          material={mat.bodendichtungConstruct1}
        />
        <mesh
          geometry={nodes.dc_bodendictung_construct_2.geometry}
          visible={visibility.boden}
          material={mat.bodendichtungConstruct2}
        />
        <mesh
          geometry={nodes.dc_bodendictung_construct_3.geometry}
          visible={visibility.boden}
          material={mat.bodendichtungConstruct3}
        />
        <mesh
          geometry={nodes.dc_vent_top.geometry}
          visible={visibility.topVent}
          material={nodes.dc_vent_top.material}
        />
        <mesh
          geometry={nodes.dc_vent_bottom.geometry}
          visible={visibility.bottomVent}
          material={nodes.dc_vent_bottom.material}
        />
      </group>

      {/* ── Frame / Zarge ── */}
      <group
        ref={frame_collection_ref}
        visible={visibility.zargen}
        scale={[doorScaleX, doorScaleY, 1]}
        dispose={null}
      >
        <mesh geometry={nodes.fc_zargen.geometry} material={mat.zargen} />
      </group>

      {/* ── Hinges / Bänder ── */}
      <group ref={bander_collection_ref} dispose={null}>
        <mesh
          geometry={nodes.bc_2_tlg_bander_top.geometry}
          visible={visibility.isbander2tlg}
          material={mat.banderTop}
        />
        <mesh
          geometry={nodes.bc_2_tlg_bander_bottom.geometry}
          visible={visibility.isbander2tlg}
          material={mat.banderBottom}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_top_top_2nd_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderTop}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_top_top_1st_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderTop}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_bottom_top_2nd_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderBottom}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_bottom_1st_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderBottom}
        />
      </group>

      {/* ── Lock — front face ── */}
      <group ref={lock_collection_front_ref} dispose={null}>
        <mesh
          geometry={nodes.lcf_front_full_lock_frame.geometry}
          visible={false}
          material={mat.frontFullLockFrame}
        />
        <mesh
          geometry={nodes.lcf_front_pzw_lock.geometry}
          visible={visibility.isPZ}
          material={mat.frontPzwLock}
        />
        <mesh
          geometry={nodes.lcf_front_handle.geometry}
          material={mat.handle}
        />
        <mesh
          geometry={nodes.lcf_front_wc_lock.geometry}
          visible={visibility.isWC}
          material={mat.frontWcLock}
        />
        <mesh
          geometry={nodes.lcf_front_bb_lock.geometry}
          visible={visibility.isBB}
          material={mat.frontBbLock}
        />
        <mesh
          geometry={nodes.lcf_front_half_lock_frame_top.geometry}
          material={mat.frontHalfLockFrameTop}
        />
        <mesh
          geometry={nodes.lcf_front_half_lock_frame_bottom.geometry}
          material={mat.frontHalfLockFrameBottom}
        />
      </group>

      {/* ── Lock — back face ── */}
      <group ref={lock_collection_back_ref} dispose={null}>
        <mesh
          geometry={nodes.lcb_back_lcb_full_lock_frame_back.geometry}
          visible={false}
          material={mat.backFullLockFrame}
        />
        <mesh
          geometry={nodes.lcb_back_pzw_lock_back.geometry}
          visible={visibility.isPZ}
          material={mat.backPzwLock}
        />
        <mesh
          geometry={nodes.lcb_back_handle_back.geometry}
          material={mat.handle}
        />
        <mesh
          geometry={nodes.lcb_back_wc_lock_back.geometry}
          visible={visibility.isWC}
          material={mat.backWcLock}
        />
        <mesh
          geometry={nodes.lcb_back_bb_lock_back.geometry}
          visible={visibility.isBB}
          material={mat.backBbLock}
        />
        <mesh
          geometry={nodes.lcb_back_half_lock_frame_top.geometry}
          material={mat.backHalfLockFrameTop}
        />
        <mesh
          geometry={nodes.lcb_back_half_lock_frame_bottom.geometry}
          material={mat.backHalfLockFrameBottom}
        />
      </group>
      {/* ── Floor ── */}
      <mesh
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, -0.05, 0]}
        receiveShadow
      >
        <planeGeometry args={[100, 100]} />
        <meshStandardMaterial
          map={floorDiff}
          displacementMap={floorDisp}
          displacementScale={0.02}
          normalMap={floorNor}
          roughnessMap={floorRough}
        />
      </mesh>
      <group
        ref={sc_schiebe_collection_ref}
        visible={doorType === DOOR_VALUES.TURTYP_OPTION.Schiebetur}
        dispose={null}
         scale={[doorScaleX, 1, 1]}
      >
        <mesh
          geometry={nodes.sc_schiebe_vor_wand.geometry}
          material={nodes.sc_schiebe_vor_wand.material}
        />
      </group>
      {/* ── Wall with door opening cut out ── */}
      {(() => {
        const isSchiebOhneZarge =
          doorType === DOOR_VALUES.TURTYP_OPTION.Schiebetur &&
          zargen === DOOR_VALUES.ZARGEN_OPTIONS.OHNE_ZARGEN;
        const cutGeom = isSchiebOhneZarge
          ? nodes.dc_door_cut.geometry
          : nodes.fc_zargen_cut.geometry;

        return (
          <group
            ref={wall_collection_ref}
            visible={visibility.wall}
            scale={[doorScaleX, doorScaleY, 1]}
          >
            <mesh>
              <meshStandardMaterial {...wallTextures} />
              <Geometry>
                <Base geometry={wallGeom} />
                <Subtraction geometry={cutGeom} />
              </Geometry>
            </mesh>
          </group>
        );
      })()}
    </group>
  );
}

useGLTF.preload("/models/door_model.glb");
