/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 door_model.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useHelper } from "@react-three/drei";
import { useDoorStore } from "@/store/door_store";
import DOOR_VALUES from "@/utils/door_config";
import {
  getHardwareColour,
  getMetrics,
  useGlassMaterial,
  useMaterial,
} from "@/utils/3d_utils/3d_utils";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/door_model.glb");

  /* ===============================
     GLOBAL STORE VALUES
  =============================== */
  const verglasung = useDoorStore((s) => s.door.verglasung);
  const doorWidth = useDoorStore((s) => s.door.width);
  const doorHeight = useDoorStore((s) => s.door.height);
  const schloss = useDoorStore((s) => s.door.schloss);
  const doorType = useDoorStore((s) => s.door.doorType);
  const anschlag = useDoorStore((s) => s.door.anschlag);
  const zargen = useDoorStore((s) => s.door.zarge);
  const band = useDoorStore((s) => s.door.band);
  const boden = useDoorStore((s) => s.door.boden);
  const vent = useDoorStore((s) => s.door.lueftung);

  const door_collection_ref = useRef();
  const frame_collection_ref = useRef();
  const lock_collection_front_ref = useRef();
  const lock_collection_back_ref = useRef();
  const bander_collection_ref = useRef();
  const rebate_edge_ref = useRef();
  const bboxHelperRef = useRef();

  useEffect(() => {
    const interval = setInterval(() => {
      const door = useDoorStore.getState().door; // ✅ read directly from store
      console.log("Door state (every 3s, direct from store):", door);
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  /* ===============================
     BASE MODEL DIMENSIONS (GLB SIZE)
  =============================== */
  const BASE_WIDTH = 900;
  const BASE_HEIGHT = 2100;

  /* ===============================
     SCALE CALCULATION
  =============================== */
  const doorScaleX = doorWidth / BASE_WIDTH;
  const doorScaleY = doorHeight / BASE_HEIGHT;

  /* ===============================
     MATERIALS
  =============================== */
  const glassMat = useGlassMaterial(verglasung);
  const hardwareMat = useMaterial(getHardwareColour(schloss));
  const BandMat = useMaterial(getHardwareColour(band));

  const mat = {
    door: materials.Material,
    glass: glassMat ?? nodes.dc_glass.material,
    handle: hardwareMat ?? nodes.lcf_front_handle.material,
    rebateEdge: nodes.dc_rebate_edge.material,
    bodendichtungFill: nodes.dc_bodendictung_fill.material,
    bodendichtungConstruct1: nodes.dc_bodendictung_construct_1.material,
    bodendichtungConstruct2: nodes.dc_bodendictung_construct_2.material,
    bodendichtungConstruct3: nodes.dc_bodendictung_construct_3.material,
    zargen: nodes.fc_zargen.material,
    banderTop: BandMat ?? nodes.bc_2_tlg_bander_top.material,
    banderBottom: BandMat ?? nodes.bc_2_tlg_bander_bottom.material,
    banderPivotTop: BandMat ?? nodes.bc_pivot_bander_top_top_1st_half.material,
    banderPivotBottom:
      BandMat ?? nodes.bc_pivot_bander_top_top_1st_half.material,
    frontFullLockFrame: hardwareMat ?? nodes.lcf_front_full_lock_frame.material,
    frontPzwLock: hardwareMat ?? nodes.lcf_front_pzw_lock.material,
    frontWcLock: hardwareMat ?? nodes.lcf_front_wc_lock.material,
    frontBbLock: hardwareMat ?? nodes.lcf_front_bb_lock.material,
    frontHalfLockFrameTop:
      hardwareMat ?? nodes.lcf_front_half_lock_frame_top.material,
    frontHalfLockFrameBottom:
      hardwareMat ?? nodes.lcf_front_half_lock_frame_bottom.material,
    backFullLockFrame:
      hardwareMat ?? nodes.lcb_back_lcb_full_lock_frame_back.material,
    backPzwLock: hardwareMat ?? nodes.lcb_back_pzw_lock_back.material,
    backWcLock: hardwareMat ?? nodes.lcb_back_wc_lock_back.material,
    backBbLock: hardwareMat ?? nodes.lcb_back_bb_lock_back.material,
    backHalfLockFrameTop:
      hardwareMat ?? nodes.lcb_back_half_lock_frame_top.material,
    backHalfLockFrameBottom:
      hardwareMat ?? nodes.lcb_back_half_lock_frame_bottom.material,
  };

  /* ===============================
     ELEMENT VISIBILITY
  =============================== */
  const visibility = {
    zargen: zargen !== DOOR_VALUES.ZARGEN_OPTIONS.OHNE_ZARGEN,
    schloss: schloss !== DOOR_VALUES.LOCK_OPTIONS.OHNE,
    boden: boden !== DOOR_VALUES.BODENDICHTUNG.OHNE_BODENDICHTUNG,
    rebateEdge: doorType === DOOR_VALUES.TURTYP_OPTION.Gefalzt,
    glass: verglasung !== DOOR_VALUES.VERGLASUNG_OPTIONS.OHNE_VERGLASUNG,
    topVent:
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.UNTEN ||
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.UNTEN_UND_OBEN,
    bottomVent:
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.OBEN ||
      vent === DOOR_VALUES.LUEFTUNGSBOHRUNG.UNTEN_UND_OBEN,

    isbander2tlg: doorType === DOOR_VALUES.TURTYP_OPTION.Gefalzt,
    isbanderPivot: doorType === DOOR_VALUES.TURTYP_OPTION.Stumpf,

    isBB: schloss.includes("BB"),
    isWC: schloss.includes("WC"),
    isPZ: schloss.includes("PZ"),
    isOhne: schloss === DOOR_VALUES.LOCK_OPTIONS.OHNE,
  };

  /* ===============================
     ANSCHLAG (MIRRORING)
  =============================== */
  const mirrorX = anschlag === DOOR_VALUES.ANSCHLAG_TYPES.DIN_RIGHT ? -1 : 1;

  /* ===============================
     BANDER METRICS — recalculate every 3 seconds
  =============================== */

  useEffect(() => {
    const door_metrics = getMetrics(door_collection_ref, {
      addBoundingBox: false,
      color: 0xff0000,
    });

    console.log("Door metrics: ", door_metrics);

    let band_pos_x = 0;
    let lock_collection_pos_x = 0;

    if (mirrorX == 1) {
      band_pos_x = door_metrics.maxX - door_metrics.maxX / doorScaleX;
      lock_collection_pos_x =
        door_metrics.minX - door_metrics.minX / doorScaleX;
    } else {
      band_pos_x = door_metrics.minX / doorScaleX - door_metrics.minX;
      lock_collection_pos_x =
        door_metrics.maxX / doorScaleX - door_metrics.maxX;
    }
    bander_collection_ref.current.position.x = band_pos_x;
    lock_collection_front_ref.current.position.x = lock_collection_pos_x;
    lock_collection_back_ref.current.position.x = lock_collection_pos_x;
  }, [doorWidth, doorHeight, anschlag]); // ✅ re-runs when anschlag changes

  /* ===============================
     FRAME POSITION — recalculate 
  =============================== */
  useEffect(() => {
    if (!frame_collection_ref.current) return;

    frame_collection_ref.current.position.z =
      doorType === DOOR_VALUES.TURTYP_OPTION.Gefalzt ? 0 : 0.01;
  }, [doorType]);

  return (
    <group {...props} scale={[mirrorX, 1, 1]} dispose={null}>
      {/* ── Door leaf ── */}
      <group
        ref={door_collection_ref}
        scale={[doorScaleX, doorScaleY, 1]}
        dispose={null}
      >
        <mesh geometry={nodes.dc_door.geometry} material={mat.door} />
        <mesh
          geometry={nodes.dc_glass.geometry}
          visible={visibility.glass}
          material={mat.glass}
        />
        <mesh
          ref={rebate_edge_ref}
          geometry={nodes.dc_rebate_edge.geometry}
          visible={visibility.rebateEdge}
          material={mat.rebateEdge}
        />
        <mesh
          geometry={nodes.dc_bodendictung_fill.geometry}
          visible={visibility.boden == false}
          material={mat.bodendichtungFill}
        />
        <mesh
          geometry={nodes.dc_bodendictung_construct_1.geometry}
          visible={visibility.boden}
          material={mat.bodendichtungConstruct1}
        />
        <mesh
          geometry={nodes.dc_bodendictung_construct_2.geometry}
          visible={visibility.boden}
          material={mat.bodendichtungConstruct2}
        />
        <mesh
          geometry={nodes.dc_bodendictung_construct_3.geometry}
          visible={visibility.boden}
          material={mat.bodendichtungConstruct3}
        />
        <mesh
          geometry={nodes.dc_vent_top.geometry}
          visible={visibility.topVent}
          material={nodes.dc_vent_top.material}
        />
        <mesh
          geometry={nodes.dc_vent_bottom.geometry}
          visible={visibility.bottomVent}
          material={nodes.dc_vent_bottom.material}
        />
      </group>

      {/* ── Frame / Zarge ── */}
      <group
        ref={frame_collection_ref}
        visible={visibility.zargen}
        scale={[doorScaleX, doorScaleY, 1]}
        dispose={null}
      >
        <mesh geometry={nodes.fc_zargen.geometry} material={mat.zargen} />
      </group>

      {/* ── Hinges / Bänder ── */}
      <group ref={bander_collection_ref} dispose={null}>
        <mesh
          geometry={nodes.bc_2_tlg_bander_top.geometry}
          visible={visibility.isbander2tlg}
          material={mat.banderTop}
        />
        <mesh
          geometry={nodes.bc_2_tlg_bander_bottom.geometry}
          visible={visibility.isbander2tlg}
          material={mat.banderBottom}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_top_top_2nd_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderTop}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_top_top_1st_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderTop}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_bottom_top_2nd_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderBottom}
        />
        <mesh
          geometry={nodes.bc_pivot_bander_bottom_1st_half.geometry}
          visible={visibility.isbanderPivot}
          material={mat.banderBottom}
        />
      </group>

      {/* ── Lock — front face ── */}
      <group ref={lock_collection_front_ref} dispose={null}>
        <mesh
          geometry={nodes.lcf_front_full_lock_frame.geometry}
          visible={false}
          material={mat.frontFullLockFrame}
        />
        <mesh
          geometry={nodes.lcf_front_pzw_lock.geometry}
          visible={visibility.isPZ}
          material={mat.frontPzwLock}
        />
        <mesh
          geometry={nodes.lcf_front_handle.geometry}
          material={mat.handle}
        />
        <mesh
          geometry={nodes.lcf_front_wc_lock.geometry}
          visible={visibility.isWC}
          material={mat.frontWcLock}
        />
        <mesh
          geometry={nodes.lcf_front_bb_lock.geometry}
          visible={visibility.isBB}
          material={mat.frontBbLock}
        />
        <mesh
          geometry={nodes.lcf_front_half_lock_frame_top.geometry}
          material={mat.frontHalfLockFrameTop}
        />
        <mesh
          geometry={nodes.lcf_front_half_lock_frame_bottom.geometry}
          material={mat.frontHalfLockFrameBottom}
        />
      </group>

      {/* ── Lock — back face ── */}
      <group ref={lock_collection_back_ref} dispose={null}>
        <mesh
          geometry={nodes.lcb_back_lcb_full_lock_frame_back.geometry}
          visible={false}
          material={mat.backFullLockFrame}
        />
        <mesh
          geometry={nodes.lcb_back_pzw_lock_back.geometry}
          visible={visibility.isPZ}
          material={mat.backPzwLock}
        />
        <mesh
          geometry={nodes.lcb_back_handle_back.geometry}
          material={mat.handle}
        />
        <mesh
          geometry={nodes.lcb_back_wc_lock_back.geometry}
          visible={visibility.isWC}
          material={mat.backWcLock}
        />
        <mesh
          geometry={nodes.lcb_back_bb_lock_back.geometry}
          visible={visibility.isBB}
          material={mat.backBbLock}
        />
        <mesh
          geometry={nodes.lcb_back_half_lock_frame_top.geometry}
          material={mat.backHalfLockFrameTop}
        />
        <mesh
          geometry={nodes.lcb_back_half_lock_frame_bottom.geometry}
          material={mat.backHalfLockFrameBottom}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/door_model.glb");
